#!/usr/bin/env bash
cat <<'EOF'
[JAL-AIDEV active] You build under the JAL constitution. Read skill jal-standards for detail.
- Runtime Bun only. No Vite, no Next.js, no heavy SSR. Any new tech needs Brian's confirmation first.
- Stack: Bun, Hono, React, TypeScript, Docker, Redis. DB self-hosted Postgres. Storage S3 (s3.datacenter.jalgroup.id). Deploy Coolify (deploy.jalgroup.id). CI GitHub Actions + gh runner + Turborepo.
- Frontend law, tidiness first. Rule 0: no overlap, ever (no text, icon, or component overlapping another, no child sticking out of its parent, no clipped text, icons never touch text). No side line on any card or panel. No shadow (depth from tonal layers and hairline borders). Default background white or off-white, never dark or colored. No em-dash, no eyebrow labels, no glow, no neon, no gradients, no emoji, no decorative lines, connectors, or marker dots, no AI slop. No big empty gaps, no empty card voids, no stretched fake-fill. Every section has a declared job; the container per region (rows, bento, section, card, spacing) is chosen by JEV. One design system everywhere: JAL Core (skill jal-design-system, Astryx foundation plus Carbon tables, forms, and notifications); never pick a different system per product. Mobile-first, 44px controls. Icons via koboyo MCP, reicon.dev fallback.
- Every project: automatic security hardening, resource-light, server-optimized.
- Only default LLM: OpenAI gpt-4o-mini.
- Routing: every non-trivial task runs on the jal-orchestration engine: jal-principal directs, jal-lead dispatches truly parallel specialists in waves (jal-ux, jal-immersive, jal-frontend, jal-backend, jal-systems, jal-architect, jal-security, jal-redteam, jal-blueteam, jal-reviewer, jal-qa, jal-devops, jal-researcher, jal-docs), jal-jev frames novel decisions. Commands (7): /jal-new start a project, /jal-build build or change anything, /jal-ui screens, redesigns, and immersive 3D sites, /jal-fix fix a bug, /jal-check one PASS or FAIL (quick, full, deep), /jal-ship PR, release, deploy, rollback, /jal-docs write or update docs.
- JEV is every agent's decision helper: every soft call goes through the jev_decide tool using the jal-jev decision catalog (46 IDs). A JEV veto is final. Decisions are logged in .jal/decisions/. On UNVERIFIED BY JEV, use own judgment and stamp the report.
- UI is proven, not promised: the ui_audit tool must PASS at 320, 375, 414, 768, and 1280 before any screen is called done. SKIPPED is never a pass.
- Hard law (jal-standards, the write-time guardrail hook, ui_audit, the checks in the review gate (/jal-check)) is mechanical and never overridable, not by JEV and not by any agent.
EOF
